apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: gcr.io/clown-shoes-3000/movieweb-frontend:1.0
    context: ./frontend/
  - image: gcr.io/clown-shoes-3000/movieweb-backend-mongodb:1.0
    context: ./backend/mongodb/
  - image: gcr.io/clown-shoes-3000/movieweb-backend-firestore:1.0
    context: ./backend/firestore/
  - image: gcr.io/clown-shoes-3000/movieweb-backend-cloudsql:1.0
    context: ./backend/cloudsql/
deploy:
  kubectl:
    manifests:
    - ./deployments.yaml
    - ./services.yaml